steps:

- id: "rodando-docker-compose"
  name: 'gcr.io/$PROJECT_ID/docker-compose'
  args: ['-f', 'docker-compose.cloudbuild.yaml', 'up', '-d']

- id: "rodando-docker-ps"
  name: 'gcr.io/cloud-builders/docker'
  args: ['ps']

- id: "executando-go"
  name: 'gcr.io/cloud-builders/go'
  args: ['run', 'greetings.go']
  env: ['GOPATH=/app']

- id: "executando-teste-unitario"
  name: 'gcr.io/cloud-builders/go'
  args: ['test', '-cover']
  env: ['GOPATH=/app']