apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-k8s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-k8s
  template:
    metadata:
      labels:
        app: go-k8s
    spec:
      containers:
      - name: go
        image: img-app-deployment
        ports:
        - containerPort: 8000